CC=g++
CFLAGS=-c -Wall
LDFLAGS=
SOURCES=./src/* 
OBJ_DIR=./obj/
BIN_DIR=./bin/
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=openbrew

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *o openbrew
